### PR TITLE
Enforce MSRV in CI

### PR DESCRIPTION
**Pull request by djc**
This crate advertises a 1.70 MSRV but generates this error:

```rust
error[E0658]: mutable references are not allowed in constant functions
  --> src/bit_vector.rs:28:22
   |
28 |     pub const fn set(&mut self, index: usize, hash: u64) -> bool {
   |                      ^^^^^^^^^
   |
   = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
```

This only works from 1.82 on.

In Quinn, we prefer to be more conservative about the MSRV (currently at 1.71, though we're bumping to 1.74 soon) so if there's a way to decrease it again, that would be nice.

### CODE REVIEW

**Comment by tomtomwombat** [comment]
Latest version should work using 1.70: https://crates.io/crates/fastbloom/0.12.1

**Comment by tomtomwombat** [comment]
I wasn't sure at the time of publishing 0.12.1 so I did a quick read through the guidelines and used this reasoning for updating fastbloom's minor version:

From https://doc.rust-lang.org/cargo/reference/rust-version.html
> Note: [Changing rust-version](https://doc.rust-lang.org/cargo/reference/semver.html#env-new-rust) is assumed to be a minor incompatibility

Since the updated function (`set`) is private, I think it would only break builds going back from fastbloom 0.12.1 to 0.12.0 in rustc version 1.70. Since there are no other changes between these 0.12.1 and 0.12.0, I don't see any strong reason why someone would prefer 0.12.0 over 0.12.1.

So I think it's ok from reading https://doc.rust-lang.org/cargo/reference/semver.html#change-categories
> Some changes are marked as “minor”, even though they carry the potential risk of breaking a build. This is for situations where the potential is extremely low

**All this is a bit subjective, so please let me know if I indeed HAVE broken anything for you and I will yank and update to 0.13.0!**

**Comment by djc** [comment]
> Since the updated function (`set`) is private, I think it would only break builds going back from fastbloom 0.12.1 to 0.12.0 in rustc version 1.70. Since there are no other changes between these 0.12.1 and 0.12.0, I don't see any strong reason why someone would prefer 0.12.0 over 0.12.1.

Ahh, you're right, sorry for missing that `BlockedBitVec::set()` is actually private. I tacked on another commit that sets the `unreachable_pub` lint to `warn` so that it's easier to see if things are public without context.
